- name: "configure {{ component }} server"
  hosts: all
  connection: local
  vars_files:
  - "variables-{{ env }}.yaml"
  become: yes
  roles:   # instead of tasks we will give roles here
  - "{{ component }}"